services:
  debian-public1:
    image: debian:12
    container_name: debian-public1
    tty: true        # 允许交互式终端
    stdin_open: true # 保持标准输入开启
    ports:
      - "22:22"
    networks:
      - my-network
    volumes:
      - ${VOLUME_PATH}/app/debian/data1:/data
      - ${VOLUME_PATH}/app/debian/init.sh:/init.sh
    command: bash -c "bash /init.sh && bash"

networks:
  my-network:  # 定义自定义网络
    name: my-network         # 可选：自定义网络名称
    driver: bridge  # 使用默认的 bridge 网络驱动
    ipam: # IP 地址管理配置（IP Address Management）
      driver: default           # 使用默认 IPAM 驱动
      config: # 子网配置（可多个）
        - subnet: 172.20.0.0/16     # 子网网段 172.20.0.1 -- 172.20.255.254
          gateway: 172.20.0.1       # 默认网关
          aux_addresses: # 预留 IP 地址
            host1: 172.20.0.2
            host2: 172.20.0.3
